//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int Id { get; set; }
        public int CollectRequestId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime AssignedAt { get; set; }
        public Nullable<System.DateTime> AcceptedAt { get; set; }
        public Nullable<System.DateTime> CollectedAt { get; set; }
        public string Note { get; set; }
    
        public virtual CollectRequest CollectRequest { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
