//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequest
    {
        public CollectRequest()
        {
            this.Assignments = new HashSet<Assignment>();
            this.Distributions = new HashSet<Distribution>();
            this.FoodItems = new HashSet<FoodItem>();
        }
    
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime MaxPreserveUntil { get; set; }
        public string Status { get; set; }
        public string EstimateQuantity { get; set; }
        public string PickupAddress { get; set; }
        public System.DateTime CreateAt { get; set; }
        public System.DateTime RequestedAt { get; set; }
    
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<Distribution> Distributions { get; set; }
        public virtual ICollection<FoodItem> FoodItems { get; set; }
    }
}
