//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZeroHungerEntities : DbContext
    {
        public ZeroHungerEntities()
            : base("name=ZeroHungerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Assignment> Assignments { get; set; }
        public DbSet<CollectRequest> CollectRequests { get; set; }
        public DbSet<Distribution> Distributions { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<FoodItem> FoodItems { get; set; }
        public DbSet<Restaurant> Restaurants { get; set; }
    }
}
